local CreatureConfig = {}

CreatureConfig.Creatures = {
	Skeleton = {
		Name = "Skeleton",
		Health = 80,
		Damage = 10,
		Defense = 5,
		Speed = 12,
		AttackRange = 6,
		AttackInterval = 1.5,
		DetectionRange = 40,
		XP = 15,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Institutional white"),
		HeadSize = Vector3.new(1.5, 1.5, 1.5),
		BodySize = Vector3.new(2, 3, 1.5),
	},
	Zombie = {
		Name = "Zombie",
		Health = 120,
		Damage = 15,
		Defense = 10,
		Speed = 8,
		AttackRange = 6,
		AttackInterval = 2.0,
		DetectionRange = 35,
		XP = 20,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Bright green"),
		HeadSize = Vector3.new(1.6, 1.6, 1.6),
		BodySize = Vector3.new(2.2, 3.2, 1.8),
	},
	Archer = {
		Name = "Archer",
		Health = 60,
		Damage = 12,
		Defense = 3,
		Speed = 10,
		AttackRange = 25,
		AttackInterval = 2.5,
		DetectionRange = 45,
		XP = 18,
		Behavior = "Ranged",
		PreferredDistance = 20,
		ProjectileSpeed = 60,
		BodyColor = BrickColor.new("Dark stone grey"),
		HeadSize = Vector3.new(1.4, 1.4, 1.4),
		BodySize = Vector3.new(1.8, 2.8, 1.4),
	},
	Spider = {
		Name = "Cave Spider",
		Health = 50,
		Damage = 8,
		Defense = 2,
		Speed = 18,
		AttackRange = 5,
		AttackInterval = 0.8,
		DetectionRange = 35,
		XP = 12,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Really black"),
		HeadSize = Vector3.new(1, 0.8, 1),
		BodySize = Vector3.new(2.5, 1.2, 2),
	},
	Wraith = {
		Name = "Wraith",
		Health = 70,
		Damage = 18,
		Defense = 0,
		Speed = 14,
		AttackRange = 7,
		AttackInterval = 1.8,
		DetectionRange = 50,
		XP = 25,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Lavender"),
		HeadSize = Vector3.new(1.6, 1.6, 1.6),
		BodySize = Vector3.new(2, 3.5, 1.5),
	},
	Mage = {
		Name = "Dark Mage",
		Health = 55,
		Damage = 20,
		Defense = 5,
		Speed = 8,
		AttackRange = 30,
		AttackInterval = 3.0,
		DetectionRange = 50,
		XP = 22,
		Behavior = "Ranged",
		PreferredDistance = 22,
		ProjectileSpeed = 50,
		BodyColor = BrickColor.new("Bright violet"),
		HeadSize = Vector3.new(1.5, 1.5, 1.5),
		BodySize = Vector3.new(2, 3, 1.5),
	},
	SkeletonKnight = {
		Name = "Skeleton Knight",
		Health = 160,
		Damage = 20,
		Defense = 20,
		Speed = 10,
		AttackRange = 7,
		AttackInterval = 1.8,
		DetectionRange = 40,
		XP = 30,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Medium stone grey"),
		HeadSize = Vector3.new(1.6, 1.6, 1.6),
		BodySize = Vector3.new(2.4, 3.4, 1.8),
	},
	Bat = {
		Name = "Giant Bat",
		Health = 40,
		Damage = 6,
		Defense = 1,
		Speed = 20,
		AttackRange = 5,
		AttackInterval = 0.7,
		DetectionRange = 45,
		XP = 10,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Dark indigo"),
		HeadSize = Vector3.new(1, 1, 1),
		BodySize = Vector3.new(1.8, 1, 2.5),
	},

	--------------------------------------------------------------------------------
	-- WARDENS: tougher creatures that guard seals
	--------------------------------------------------------------------------------
	IronKeeper = {
		Name = "Iron Keeper",
		Health = 300,
		Damage = 22,
		Defense = 25,
		Speed = 9,
		AttackRange = 7,
		AttackInterval = 1.5,
		DetectionRange = 45,
		XP = 60,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Medium stone grey"),
		HeadSize = Vector3.new(2, 2, 2),
		BodySize = Vector3.new(3, 4.5, 2.5),
	},
	GoldGuardian = {
		Name = "Gold Guardian",
		Health = 350,
		Damage = 25,
		Defense = 28,
		Speed = 8,
		AttackRange = 7,
		AttackInterval = 1.6,
		DetectionRange = 45,
		XP = 65,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Bright yellow"),
		HeadSize = Vector3.new(2, 2, 2),
		BodySize = Vector3.new(3.2, 4.8, 2.6),
	},
	CrimsonSentinel = {
		Name = "Crimson Sentinel",
		Health = 400,
		Damage = 28,
		Defense = 22,
		Speed = 11,
		AttackRange = 7,
		AttackInterval = 1.4,
		DetectionRange = 50,
		XP = 70,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Bright red"),
		HeadSize = Vector3.new(2.2, 2.2, 2.2),
		BodySize = Vector3.new(3.4, 5, 2.8),
	},
	EmeraldWarden = {
		Name = "Emerald Warden",
		Health = 320,
		Damage = 30,
		Defense = 15,
		Speed = 9,
		AttackRange = 28,
		AttackInterval = 2.5,
		DetectionRange = 50,
		XP = 70,
		Behavior = "Ranged",
		PreferredDistance = 22,
		ProjectileSpeed = 55,
		BodyColor = BrickColor.new("Dark green"),
		HeadSize = Vector3.new(2, 2, 2),
		BodySize = Vector3.new(3, 4.5, 2.5),
	},
	ShadowChampion = {
		Name = "Shadow Champion",
		Health = 450,
		Damage = 30,
		Defense = 30,
		Speed = 10,
		AttackRange = 8,
		AttackInterval = 1.5,
		DetectionRange = 50,
		XP = 80,
		Behavior = "Melee",
		BodyColor = BrickColor.new("Really black"),
		HeadSize = Vector3.new(2.2, 2.2, 2.2),
		BodySize = Vector3.new(3.5, 5.2, 2.8),
	},

	--------------------------------------------------------------------------------
	-- SANCTUM BOSS
	--------------------------------------------------------------------------------
	BossGolem = {
		Name = "Stone Golem",
		Health = 800,
		Damage = 25,
		Defense = 30,
		Speed = 6,
		AttackRange = 8,
		AttackInterval = 2.0,
		DetectionRange = 60,
		XP = 200,
		Behavior = "Boss",
		BodyColor = BrickColor.new("Dark grey"),
		HeadSize = Vector3.new(3, 3, 3),
		BodySize = Vector3.new(5, 6, 4),
		SlamCooldown = 15,
		SlamRadius = 15,
		SlamDamage = 40,
		SlamWarningTime = 1.5,
		SummonAtHealthPercent = 0.5,
		SummonCount = 2,
		SummonType = "Skeleton",
		Phases = {
			{
				Threshold = 0.75,
				Name = "Phase 2",
				BodyColor = BrickColor.new("Medium stone grey"),
				SpeedMultiplier = 1.2,
				SlamCooldown = 12,
				SlamDamage = 50,
			},
			{
				Threshold = 0.50,
				Name = "Phase 3 - Enraged",
				BodyColor = BrickColor.new("Bright orange"),
				SpeedMultiplier = 1.4,
				SlamCooldown = 10,
				SlamDamage = 60,
				SummonCount = 3,
				SummonType = "SkeletonKnight",
			},
			{
				Threshold = 0.25,
				Name = "Phase 4 - Berserk",
				BodyColor = BrickColor.new("Bright red"),
				SpeedMultiplier = 1.6,
				SlamCooldown = 8,
				SlamDamage = 70,
			},
		},
	},
}

return CreatureConfig
